version: "3"
services:
  sloth-js:
    build:
      context: ./src/sloth-js
    ports:
      - "8080:80"
    networks: 
      - sloth-net
  
  sloth-api:
    build:
      context: ./src/sloth-backend/sloth-api
    ports:
      - "8081:8080"
    networks:
      - sloth-net

volumes:
  metabase:

networks: 
  sloth-net:
    driver: bridge